[package]
name = "goad-rust-batt-reminder"
version = "1.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "*"
rodio = "*"
serde = "*"
toml = "*"
serde_derive = "*"
